integrations/hardhat: explicitly add @types/node
This should resolve the issue encountered during CI:

	Error: ../../node_modules/.pnpm/ethers@6.6.2/node_modules/ethers/lib.commonjs/providers/provider-ipcsocket.d.ts(1,23): error TS4090: Conflicting definitions for 'node' found at '/home/runner/work/sapphire-paratime/sapphire-paratime/node_modules/.pnpm/@types+node@18.15.13/node_modules/@types/node/index.d.ts' and '/home/runner/work/sapphire-paratime/sapphire-paratime/node_modules/.pnpm/@types+node@18.16.18/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.
	  The file is in the program because:
	    Type library referenced via 'node' from file '/home/runner/work/sapphire-paratime/sapphire-paratime/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/base-provider.d.ts' with packageId '@types/node/index.d.ts@18.16.18'
	    Type library referenced via 'node' from file '/home/runner/work/sapphire-paratime/sapphire-paratime/node_modules/.pnpm/ethers@6.6.2/node_modules/ethers/lib.commonjs/providers/provider-ipcsocket.d.ts' with packageId '@types/node/index.d.ts@18.15.13'